Django Level Five/myproject/myApp/urls.py
from django.contrib import admin
from django.urls import path, include
from myApp import views

app_name = 'myApp'

urlpatterns = [
    path('register/', views.register, name='register'), ## View "register" function needs to be set up
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
]

Django Level Five/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from myApp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('myApp/', include('myApp.urls')), 
]

Django Level Five/myproject/myApp/models.py
from pyexpat import model
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.DO_NOTHING) ## Connects to auth user model

    ## Additional Class
    portfolioSite = models.URLField(unique = True, blank = True)
    profilePic = models.ImageField(upload_to = 'profilePics', blank = True)

    def __str__(self):
        return str(self.user.username)

Django Level Five/myproject/myApp/forms.py
from django import forms
from django.contrib.auth.models import User
from myApp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portfolioSite', 'profilePic')

Django Level Five/myproject/myApp/views.py
from django.shortcuts import render
from myApp.forms import UserForm, UserProfileInfoForm

## Login Imports
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout

def index(request):
    return render(request, 'myApp/index.html')

## This decorator makes sure that a user is logged in
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    registered = False

    if request.method == 'POST':
        userForm = UserForm(data = request.POST)
        profileForm = UserProfileInfoForm(data = request.POST)

        if userForm.is_valid() and profileForm.is_valid():

            user = userForm.save() # Save User
            user.set_password(user.password) # Hash Password
            user.save() # Saves it

            # This is needed for the one to one relationship with User model
            profile = profileForm.save(commit=False)
            profile.user = user 

            # For files such as images, csv's, etc. you need to find these through REQUEST.FILES
            if 'profilePic' in request.FILES:
                profile.profilePic = request.FILES['profilePic']
            
            profile.save()

            registered = True
        else:
            print(userForm.errors, profileForm.errors)
    else:
        userForm, profileForm = UserForm(), UserProfileInfoForm()

        
    return render(request, 'myApp/registration.html', context = {'userForm': userForm, 
                                                                 'profileForm':profileForm, 
                                                                 'registered': registered
                                                                 })
        

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username, password = password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Your account has been deactivated')
        else:
            print('Failed Login')
            print('Username: ', username)
            return HttpResponse('Invalid Login Details Supplied')
    else:
        return render(request, 'myApp/login.html')

Django Level Five/myproject/templates/myApp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li>
                    <a class="navbar-brand" href="{% url 'index' %}">Home Page</a>
                </li>
                <li>
                    <a class="navbar-link" href="{% url 'admin:index' %}">Admin Site</a>
                </li>
                <li>
                    <a class="navbar-link" href="{% url 'myApp:register' %}">Register</a>
                </li>

                {% if user.is_authenticated %}
                    <li>
                        <a class="navbar-link" href="{% url 'myApp:logout' %}">
                            Log Out
                        </a>
                    </li>
                {% else %}
                    <li>
                        <a class="navbar-link" href="{% url 'myApp:login' %}">
                            Log In
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    {% block body_block %}

    {% endblock %}
</body>
</html>

Django Level Five/myproject/templates/myApp/index.html
{% extends 'myApp/base.html' %}

{% block body_block %}
<div class = 'jumbotron'>
    <h1>
        Django Level Five
    </h1>
</div>
{% endblock %}

Django Level Five/myproject/templates/myApp/login.html
{% extends 'myApp/base.html' %}

{% block body_block %}
    <div class="jumbotron">
        <form method="post" action="{% url 'myApp:login' %}">
            {% csrf_token %}

            <label for="username">Username</label>
            <input type="text" name="username" placeholder="Enter Username">
            
            <label for="password">Password</label>
            <input type="password" name="password">

            <input type="submit" value="Log In">
        </form>
    </div>

{% endblock %}

Django Level Five/myproject/templates/myApp/registration.html
{% extends 'myApp/base.html' %}
{% load static %}

{% block body_block %}
<div class="jumbotron">
    {% if registered %}
        <h1>Thanks for registering!</h1>
    {% else %}
        <h1>Register Here!</h1>
        <h3>Fill out the form</h3>
        <form method="post" enctype="multipart/form-data"> <!-- enctype="multipart/form-data" used for forms with image data -->
            {% csrf_token %} <!--  Used always in a form -->

            {{ userForm.as_p }} <!--  Both defined in the context dictionary -->
            {{ profileForm.as_p }}

            <input type="submit" value="Register" class="btn btn-primary">
        </form>
    {% endif %}
    
</div>
    
{% endblock %}